### ISSUE TITLE
IndexOutOfBoundError When Executing RigidFall Evaluation

### ISSUE THREAD

**Issue by qingfengtommy** [hanjq17/SGNN#1]
Hi hanjq:

Thank you so much for your open-source code.
I am trying to replicate the experiment results of RigidFall dataset.
However, after training the model, when I am trying to evaluate on validation datasets, I encountered following errors:

```
model_kp #params: 1550625
Loading network from /home1/user/gnn_exp/exp_logs/SGNN/RigidFall/SGNN_5000_dy_nHis2_aug0.05/net_best.pth
Rollout 0 / 500
Traceback (most recent call last):
  File "/home1/user/gnn_exp/SGNN/RigidFall/eval_new.py", line 113, in <module>
    group_gt = get_env_group(args, n_particle, scene_params, use_gpu=use_gpu)
  File "/home1/user/gnn_exp/SGNN/RigidFall/data_new.py", line 455, in get_env_group
    norm_g = normalize_scene_param(scene_params, 1, args.physics_param_range)
  File "/home1/user/gnn_exp/SGNN/RigidFall/data_new.py", line 122, in normalize_scene_param
    normalized = np.copy(scene_params[param_idx])
IndexError: index 1 is out of bounds for dimension 0 with size 1
```

**Comment by hanjq17** [comment]
Hi,
Thanks for reporting the error. However, at this time I cannot reproduce and locate the problem. It seems that the data you are using for the validation datasets contain inappropriate `scene_params`, in that `scene_params` do not have the gravity parameter at `param_idx`=1, which contributes to the error you're encountering.
However, since it seems that you have completed the training, the training data must have this gravity parameter. It's a little bit weird.

Could you re-check your data/code to provide me with more info? Especially to check the `scene_params` to see whether the validation data you're using aligns with the training data format.

Thanks.
Jiaqi

**Comment by qingfengtommy** [comment]
Hi jiaqi, thank you so much for your help!  I fixed this issue by revising the normlize funciton in data_new.py. It seems like this is due the difference between the tensor shape in training session and evaluating session,

**Comment by hanjq17** [comment]
Hi qingfeng,
Thank you for fixing it! 
If you find that it is indeed a bug in the code, feel free to let me know and I am willing to fix it. There might be something edited by mistake during cleaning code before open-source.

Best,
Jiaqi

**Comment by qingfengtommy** [comment]
Hi jiaqi,

No worries, I will recheck it later to determine if it is indeed a bug. Currently, I am working on implementing experiments with the Physion datasets. However, I find myself a bit perplexed by the testing data directory. I want to confirm the structure of the datasets.

The data structure mentioned in the Physion repository appears as follows:
```
# hostname:
#     username:
#         training_data_dir: directory where you download your training hdf5 files
#              |___ Dominoes
#                      |__ pilot_ooo_xxx.hdf5
#                      |__ pilot_ooo_xxx.hdf5
#                      |__ pilot_ooo_xxx.hdf5
#                      |__ pilot_ooo_xxx.hdf5
#                      |__ ...
#              |___ Collide
#              |___ Drop
#              |___ ...
#         testing_data_dir: directory where you download your training hdf5 files
#              |___ Dominoes
#                      |__ pilot_ooo_xxx.hdf5
#                      |__ pilot_ooo_xxx.hdf5
#                      |__ pilot_ooo_xxx.hdf5
#                      |__ pilot_ooo_xxx.hdf5
#                      |__ ...
#              |___ Collide
#              |___ Drop
#              |___ ...
#         dpi_data_dir: directory where you plan to store the preprocessed data for DPI
#         out_dir: directory for dumping model, log, and visualization
``` 
However, when I unzip the compressed file for the testing_data_dir, I see something like this:
```
#         testing_data_dir: directory where you download your training hdf5 files
#              |___ Dominoes
#                      |__hdf5s
#                          |__ pilot_ooo_xxx.hdf5
#                          |__ pilot_ooo_xxx.hdf5
#                          |__ pilot_ooo_xxx.hdf5
#                          |__ pilot_ooo_xxx.hdf5
#                      |__hdf5s-redyellow
#                          |__ ...
```
Could you please clarify the difference between "hdf5s" and "hdf5s-redyellow"? Is it correct for me to move the data from "hdf5s" under the Dominoes directory and use it as the testing dataset?
Additionally, could you provide the data structure for the dpi_data_dir?
Is it 
```
#          dpi_data_dir:
#              |___ Dominoes
#                      |___train
#                      |___test
#              |____Collide
#                      |___train
#              |____.....
```
or is it
```
#          dpi_data_dir:
#              |___ train
#                      |___Dominoes
#                      |___Collide
#              |____test
#                      |___Dominoes
#                      |___Collide
```
Thank you very much for your help!

Best,
Tommy

**Comment by hanjq17** [comment]
Hi qingfeng,

For the first question, though I couldn't clearly remember which one I used, I think you can use either of them. They are the same data while the one with `redyellow` tag indicates that it has the objects to be detected for collision marked in red and yellow, for vision models to recognize. They are indeed the same trajectory. You can use either of them safely unless there is an error triggered when you run the code.

For the second, it's like:
`xxx/data_RigidFall/train/xxx` and  `xxx/data_RigidFall/test/xxx`

**Comment by qingfengtommy** [comment]
Got it! Thanks !
