### ISSUE TITLE
How to use my own point cloud to train and how to decide the new common data (std_d mean__d std_p mean_p)

### ISSUE THREAD

**Issue by rickkkzzz** [hanjq17/SGNN#2]
Hi!
 I 'm training my own data point cloud with your SGNN model which has 3D positions at different time.  
 
![微信图片_20240413141717](https://github.com/hanjq17/SGNN/assets/115083243/02eebc08-7909-4caa-a008-07d33c1a66bd)

However, I 'm confused about the setting of std_d mean__d std_p mean_p. Should set them different from Rigidfall dataset (where I know the std_d...)? How should I set them?

Thank you!

**Comment by hanjq17** [comment]
Hi!

Thanks for raising the question!

The role of the mean and std here is to normalize some quantity to zero mean and unit standard deviation when that quantity is computed over all training samples. So basically a principled way to set the mean and std would be to traverse all training data point in the data loader and record the distribution of the quantity you want to normalize, and compute its mean and std to be the mean and std you want to apply in the normalization.

Yet, specifically for the values set in RigidFall dataset, I was directly using that from the original codebase of DPI-Net so I never checked the exact way it was computed. However, the method I described above could be adopted anyways as a baseline strategy.

Please let me know if I can help more on this.

Best,
Jiaqi

**Comment by rickkkzzz** [comment]
So much thanks for answering!
I decide to normalize the quantity of each squence scene such as dropping a box according to your explaination.
![std](https://github.com/hanjq17/SGNN/assets/115083243/5574e594-31f7-413a-a489-cc4952ad48f0)
